Add sensor viewing angles
stactools-packages/sentinel2 pull request #86
Opened 2023-02-02 14:25 UTC by gadomski

## Description

Uses `Mean_Viewing_Incidence_Angle_List` in the granule metadata to add sensor azimuth and zenith to each asset, when available.

Requesting @matthewhanson's review to check the following:
- That I'm using the `view` extension correctly
- That I'm doing the `bandId` (which are just integers) to `band` (strings, including `8A`) correctly

## Related issues

- Closes #50

2023-02-07 22:53 UTC, matthewhanson requested changes
This just needs to be updated to populate `view:incidence_angle` instead of `view:off_nadir` as indicated above.

It would be nice to have the off_nadir angle as well, but I think we'd want the actual sat altitude rather than the mean value of 786km, it's then:

view:off_nadir = arcSin [ (R * sin(180-view:incidence_angle))/ (R + h) ]

where
R: radius of earth
h: satellite altitude

The bandIds all look fine, I double checked the product metadata and it's just a 0-based index of the bands, where B1 is bandId 0, B8A is then bandId 8, and after that it's X=BX

2023-02-08 15:09 UTC, gadomski commented on src/stactools/sentinel2/stac.py
> +        asset.extra_fields["view:off_nadir"] = viewing_angle.zenith
I looked at `incidence_angle` and it didn't seem to fit:

> The incidence angle is the angle between the vertical (normal) to the intercepting surface and the line of sight back to the satellite at the scene center. Measured in degrees (0-90).

By this wording, I need to know the slope and aspect of the intercepting surface to calculate the incidence angle, no?

2023-02-08 16:14 UTC, matthewhanson commented on src/stactools/sentinel2/stac.py
> +        asset.extra_fields["view:off_nadir"] = viewing_angle.zenith
I can see the confusion, but the incidence angle in this case isn't taking into account terrain, It's just the tangent to the earth surface assuming a spherical earth.

2023-02-08 20:45 UTC, gadomski commented
> we'd want the actual sat altitude

I couldn't find this value in any obvious spots, and searching the test files for "elevation", "height", and "altitude" also turned up blank. Do you know if the sat altitude is provided in the metadata somewhere I haven't found?

2023-02-27 15:51 UTC, matthewhanson commented
@gadomski I looked around, but I don't see where it is in the metadata. 
However, the mean altitude could be used here - the sensor is only collecting within a fairly narrow set of altitudes to achieve the needed resolution.

For Sentinel-2 the mean altitude is given as 786km, although this paper says the min is 788km at 15deg, and 818km at 81deg - https://www.isprs-ann-photogramm-remote-sens-spatial-inf-sci.net/V-1-2022/57/2022/isprs-annals-V-1-2022-57-2022.pdf

With that small altitude range there won't be much impact on the view:off_nadir calculation

2023-04-03 11:21 UTC, pjhartzell approved these changes
LGTM

2023-04-03 12:10 UTC, merged